// <auto-generated />
using ErrorTranspose.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErrorTranspose.Migrations
{
    [DbContext(typeof(ErrorDbContext))]
    partial class ErrorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErrorTranspose.Models.Error", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorId"));

                    b.Property<string>("CodeErreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeErreur2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeErreur3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeErreur4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureErreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureErreur2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureErreur3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureErreur4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ErrorId");

                    b.ToTable("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
